name: Android Build APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  MAIN_MODULE: app

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout sources
      uses: actions/checkout@v4
    
    # Set up Java 17 (2025 standard)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    # Set up Gradle (latest approach)
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    
    # Make gradlew executable
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    # Run tests
    - name: Run tests
      run: ./gradlew test
    
    # Build debug APK
    - name: Build debug APK
      run: ./gradlew assembleDebug
    
    # Build release APK (unsigned)
    - name: Build release APK
      run: ./gradlew assembleRelease
    
    # Upload debug APK as artifact
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: ${{ env.MAIN_MODULE }}/build/outputs/apk/debug/*.apk
        retention-days: 30
    
    # Upload release APK as artifact
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: ${{ env.MAIN_MODULE }}/build/outputs/apk/release/*.apk
        retention-days: 30

  # Optional: Create GitHub release with APK
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download release APK
      uses: actions/download-artifact@v4
      with:
        name: release-apk
        path: ./
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.apk'
        generate_release_notes: true